"""`euthyna submit` — package your local Euthyna telemetry for community submission.

Everything packaged here was generated by the Euthyna gateway itself, so the shape
is known and the privacy floor is structural: ledgers carry numbers and flags,
traces carry hashes and sizes — no message content exists in either. This command
adds four more guarantees on top:

1. Session ids are re-mapped to s001, s002, … (the mapping never leaves your machine).
2. Profile base_urls that are not localhost are redacted to their scheme.
3. A content-leak guard refuses to package any unexpectedly long string field.
4. You see a full preview (counts + a sample row) and must confirm before anything
   is written. Nothing is uploaded — the output is an offline tarball you submit
   yourself (see the printed instructions).
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import io
import json
import tarfile
from pathlib import Path

from euthyna.ledger import home
from euthyna.version import __version__

# Ledger/trace string fields that are allowed to be long-ish (everything else
# caps at _MAX_STR — the guard against content sneaking into a metadata field).
_ALLOWED_LONG = {"cost_error"}
_MAX_STR = 120

TIER = "hash-only"  # v0 ships the zero-content tier only


def _guard_strings(obj, where: str) -> None:
    if isinstance(obj, dict):
        for k, v in obj.items():
            if isinstance(v, str) and len(v) > _MAX_STR and k not in _ALLOWED_LONG:
                raise ValueError(
                    f"content-leak guard: field {k!r} in {where} is {len(v)} chars — "
                    "refusing to package")
            _guard_strings(v, where)
    elif isinstance(obj, list):
        for v in obj:
            _guard_strings(v, where)


def _redact_base_url(url: str) -> str:
    if "127.0.0.1" in url or "localhost" in url:
        return url
    scheme = url.split("://", 1)[0] if "://" in url else "https"
    return f"{scheme}://<redacted>"


def collect(home_dir: Path, date_from: str, date_to: str) -> dict:
    """Gather, sanitize, and validate everything in the submission window."""
    session_map: dict[str, str] = {}

    def anon(session: str) -> str:
        if session not in session_map:
            session_map[session] = f"s{len(session_map) + 1:03d}"
        return session_map[session]

    ledgers = {}
    for f in sorted((home_dir / "ledger").glob("*.jsonl")):
        if not (date_from <= f.stem <= date_to):
            continue
        rows = []
        for line in f.read_text().splitlines():
            try:
                row = json.loads(line)
            except ValueError:
                continue
            row["session"] = anon(row.get("session") or "?")
            _guard_strings(row, f"ledger/{f.name}")
            rows.append(row)
        if rows:
            ledgers[f.name] = rows

    traces = {}
    for f in sorted((home_dir / "traces").glob("*.jsonl")):
        events = []
        for line in f.read_text().splitlines():
            try:
                e = json.loads(line)
            except ValueError:
                continue
            if not (date_from <= e.get("ts", "")[:10] <= date_to):
                continue
            _guard_strings(e, f"traces/{f.name}")
            events.append(e)
        if events:
            traces[anon(f.stem) + ".jsonl"] = events
    return {"ledgers": ledgers, "traces": traces, "n_sessions": len(session_map)}


def summarize(bundle: dict) -> dict:
    rows = [r for rows in bundle["ledgers"].values() for r in rows]
    prompt = sum((r.get("usage") or {}).get("prompt_tokens") or 0 for r in rows)
    completion = sum((r.get("usage") or {}).get("completion_tokens") or 0 for r in rows)
    return {
        "tier": TIER,
        "euthyna_version": __version__,
        "calls": len(rows),
        "sessions": bundle["n_sessions"],
        "prompt_tokens": prompt,
        "completion_tokens": completion,
        "models": sorted({r.get("model") for r in rows if r.get("model")}),
        "ledger_days": sorted(bundle["ledgers"]),
    }


def write_bundle(bundle: dict, manifest: dict, out_dir: Path) -> Path:
    payload = json.dumps(manifest, sort_keys=True).encode()
    sid = hashlib.sha256(payload).hexdigest()[:10]
    manifest = {**manifest, "submission_id": sid}
    out = out_dir / f"euthyna-submission-{sid}.tar.gz"
    out_dir.mkdir(parents=True, exist_ok=True)
    with tarfile.open(out, "w:gz") as tar:
        def add(name: str, text: str) -> None:
            data = text.encode()
            info = tarfile.TarInfo(name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))

        add("MANIFEST.json", json.dumps(manifest, indent=2))
        for fname, rows in bundle["ledgers"].items():
            add(f"ledger/{fname}", "\n".join(json.dumps(r) for r in rows))
        for fname, events in bundle["traces"].items():
            add(f"traces/{fname}", "\n".join(json.dumps(e) for e in events))
    return out


def run(args) -> int:
    home_dir = home()
    date_to = args.to_date or _dt.date.today().isoformat()
    date_from = args.from_date or date_to
    try:
        bundle = collect(home_dir, date_from, date_to)
    except ValueError as exc:
        print(f"submit: BLOCKED — {exc}")
        return 1
    manifest = summarize(bundle)
    if not manifest["calls"]:
        print(f"submit: no ledger rows in {date_from}..{date_to} under {home_dir}")
        return 0

    print(f"submit: preview ({date_from}..{date_to}, tier: {TIER} — no message content exists in this data)")
    for k, v in manifest.items():
        print(f"  {k}: {v}")
    sample = next(iter(bundle["ledgers"].values()))[0]
    print(f"  sample ledger row: {json.dumps(sample)[:200]}...")
    if not args.yes:
        answer = input("Package exactly this? [y/N] ").strip().lower()
        if answer != "y":
            print("submit: aborted, nothing written")
            return 0
    out = write_bundle(bundle, manifest, Path(args.out))
    print(f"submit: wrote {out}")
    print("submit: next step — attach this file to a submission issue at the community "
          "traces repository (see README), or share it with your Euthyna contact. "
          "Nothing has been uploaded.")
    return 0
